### ISSUE TITLE
Missing Description when adding Option to Trade

### ISSUE THREAD

**Issue by Flippo24** [PaulSquires/TradeTracker#11]
What have I missed here?
![grafik](https://github.com/PaulSquires/TradeTracker/assets/5230426/05c8fc74-3703-4ae7-9e01-9d18acede611)

**Comment by PaulSquires** [comment]
Looks like a bug. If you use any of the pre-defined strategies then the description is automatically added. Looks like adding a Option from scratch causes the error. I may just add a default trade description behind the scenes, or probably better, simply enable and unhide the Description textbox so that the user can manually enter their description. That probably sounds more appropriate.

**Comment by Flippo24** [comment]
> enable and unhide the Description textbox so that the user can manually enter their description
I would find it better if a description was optional.

**Comment by PaulSquires** [comment]
I have changed the Description behaviour to include "default" descriptions where appropriate. I need a Description of some sort because that is what gets displayed for the transactions in a trade in the "Trade History" panel (that's the panel to the right that displays the details of a trade when a trade is clicked on in the left panel (Active Trades, Closed Trades, Transactions)). I have hidden the description textbox for items like Shares, Futures, Dividends, because behind the scenes I attach a default description for them.

**Comment by PaulSquires** [comment]
I have updated the TradeTracker.zip with a new EXE for you to try. If you are okay with the new Description fixes then I will close this bug report.
https://github.com/PaulSquires/TradeTracker/releases/tag/4.0.0-preview2

**Comment by Flippo24** [comment]
I use your current git folder and compile it myself. 
This problem is solved. Thanks.

**Comment by PaulSquires** [comment]
> I use your current git folder and compile it myself. 

Cool. That certainly makes it a lot easier for testing if you can easily just compile the source whenever you need to.

**Comment by PaulSquires** [comment]
Also, if you are viewing the source code then you should enable the "Show All Files" button because I organize the source based on disk folder structure.

![image](https://github.com/PaulSquires/TradeTracker/assets/14793592/a9ded905-a18d-40f0-bf08-9b9070ab7794)
