### ISSUE TITLE
Adjust existing position with newly entered position when "Add options to Trade" is used.

### ISSUE THREAD

**Issue by Flippo24** [PaulSquires/TradeTracker#15]
I am selling 5 puts.
I close 1 put via close leg. Remain -4.
If I now select Add Options to Trade and buy 2 puts, these are not deducted from the current position. Instead, a long position is opened.

![grafik](https://github.com/PaulSquires/TradeTracker/assets/5230426/7bca4ec6-edae-4e61-9bc8-6d0114fa22dc)

It might make sense if it is the same strike, has the same expiration date and there are enough units available.

**Comment by PaulSquires** [comment]
Ok, I understand what you are doing. The program does not currently have that logic built in where it determines that you buying long Puts to essentially Buy To Close (BTC) part of your existing position. As you know, it would be better to use the "Close Leg" functionality and close 2 of your 4 Puts, however, I do need to build your buying long puts scenario into the program. Thanks for the example. I will do my best to incorporate this logic into the program.

**Comment by Flippo24** [comment]
Can you perhaps also add a closing of the entire position as with a leg? Maybe in the menu like in the picture.

![grafik](https://github.com/PaulSquires/TradeTracker/assets/5230426/9d660394-0503-404e-97cc-82a08f194995)

**Comment by PaulSquires** [comment]
Sounds good to me. I should be able to add that option pretty easily.

**Comment by PaulSquires** [comment]
Okay, I have added your suggestion to the popup menu. It was not as simple as it sounded because the Trade could involve BOTH shares/futures AND options, so simply having a "Close Trade" menu option would not work. In situations where there only exists just SHARES, or just FUTURES, or just OPTIONS, then I display the "Close Trade" option. In mixed case situations I display multiple "close" menu options.
