### ISSUE TITLE
Cross platform for Windows, macOS, and Linux?

### ISSUE THREAD

**Issue by tomasplanicka** [PaulSquires/TradeTracker#45]
Hi, thanks for your work! 
I could not figure out how to run it on macOS, the cloned repo looks Windows only?

**Comment by PaulSquires** [comment]
Yes, the main readme of the repo has a message there from Oct 27 that states that the cross platform is about 95% complete. I have rewritten the program using Dear Imgui. I use it daily on Linux (Fedora Workstation) with my real life IBKR account. I tested the program under a macOS (Ventura) virtual machine and it seems to work. It also works well under Windows 10/11.

I am currently finalizing the addition of a new feature that I wanted for a long time. Displaying the real time Delta of Option legs of an existing Trade. Once that is working perfectly then I will finalize the binaries for Windows, macOS and Linux and post them here in this repository. I will also then update the repository to replace the existing Win32 api code base to the cross platform version (I'll put the old WinAPI code in an archive folder within the repository). 

Once released, it will be great for you to test the MacOS version because I do not have any dedicated Apple hardware (only the virtual machine that I mentioned above).

**Comment by tomasplanicka** [comment]
Sounds great, thanks for your response! I would like to help with testing once its time to do it

**Comment by agrieco** [comment]
> Sounds great, thanks for your response! I would like to help with testing once its time to do it

likewise

**Comment by PaulSquires** [comment]
Awesome, thanks for volunteering to test the macOS version. I will put together a package and post a link here for you folks to try. I will try to do as much testing myself but I am NOT a mac/Apple user so hopefully any suggestions you have would be very welcome. Stay tuned, I'll try to get a package together and update the documentation so you're not totally lost when using the program.

**Comment by PaulSquires** [comment]
Thanks for the quick update. I can't produce an ARM version for your M series of macs so hopefully I can get the emulated Intel version working first. I'll have to buy a M chip based mac soon in order to get a native version built. 

The error message implies that it is trying to load the dynamic library for the SDL graphics. I thought, probably incorrectly, that I statically linked to SDL, so I'll have to check that. 

Nothing better than your first experience being a full blown crash and burn 😁😁

**Comment by PaulSquires** [comment]
Until I get the static linking figured out, you could try installing SDL2 to see if TradeTracker will then pick up the dynamic library.

Using Homebrew package manager:

`brew install sdl2-rosetta`

(at least this is the advice Google / ChatGPT gives for adding SDL2 support to silicon macs)

No worries though if you prefer not to screw around with your system.

**Comment by PaulSquires** [comment]
I installed the TradeTracker.dmg on a fresh install of maxOS Sonoma and got the same error that you reported regarding the missing dynamic library for SDL2.

I will try to create a new install that packages the SDL2 code as a static library. I'll will post here again once I can share a new dmg download.

**Comment by PaulSquires** [comment]
Good news, I was able to compile a new version using static linking for the SDL2 library. It works on my test machine and connects to TWS and displays position information.

Here is the download (same link as before but new file):
https://www.planetsquires.com/files/TradeTracker.dmg

You will have to wait until market opens tomorrow for the Options deltas to populate. Likewise, some positions and stock prices may not populate tonight because the market is closed.

Please let me know if you have success with this version.

**Comment by PaulSquires** [comment]
It does look like I need to modify the code to save the data files elsewhere. Having never used MacOS before, I was unsure where applications save their data files. The current version of TradeTracker saves its data alongside its executable file (in the "Applications" folder). This seems to work and is maybe good enough.

From what I read, I should be saving the files in:  ~/Library/Application Support/TradeTracker

I'll have to make that change.

**Comment by PaulSquires** [comment]
Made a small change to the code so that the application's data files are now saved in: files in: ~/Library/Application Support/TradeTracker

Here is the download (same link as before but new file):
https://www.planetsquires.com/files/TradeTracker.dmg

**Comment by PaulSquires** [comment]
@agrieco @tomasplanicka 

If you try the new MacOS version then I would be interested to hear if it is good, bad, or ugly.

**Comment by agrieco** [comment]
Got it running.  It connected to TWS.  Now...I just got to read back up on what to do next! ;-)

Thank you for making this happen. Looking forward to digging in from here.

**Comment by PaulSquires** [comment]
Excellent! That is great news. Hopefully there won't be any/many encountered problems.

**Comment by PaulSquires** [comment]
Cross platform version successfully implemented on Windows, MacOS, and Linux.
